name: Deploy Dockerized LAMP Stack on Staging Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploying To Staging Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: ~/
        remote_host: ${{ secrets.STAGING_SERVER_IP }}
        remote_user: ubuntu
        remote_key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}

    - name: Installing Docker on Assignment/Test Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg 
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo docker run hello-world

    - name: Find and Change Directory to docker-compose.yml
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          path=$(find / -name "docker-compose.yml" 2>/dev/null)
          if [ -n "$path" ]; then
            cd "$(dirname "$path")" || exit 1
          else
            echo "docker-compose.yml not found"
            exit 1
          fi

    - name: Run Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.STAGING_SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker-compose up -d
